// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0

package db

type Datum struct {
	ID    int32
	Name  string
	Email string
}

type User struct {
	ID       int32
	Username string
	Password string
}
